#!/bin/bash

if [ -z ${DOCKER_TAG} ]; then
  echo "Building tag ${DOCKER_TAG}"
  docker build -t $IMAGE_NAME -f $DOCKER_TAG/Dockerfile .
else
  echo "Building latest"
  docker build -t $IMAGE_NAME -f latest/Dockerfile .
fi

